default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: hangman_development


production:
  <<: *default
  host: <%= ENV['ec2-23-21-13-88.compute-1.amazonaws.com'] %>
  database: <%= ENV['d373saji797ipt'] %>
  username: <%= ENV['xmrhioyeznlekd'] %>
  password: <%= ENV['6f7247ebb5987ef7afd956b03b6b0ab199eeb494c0e325e35644f41d521a57c5'] %>